# Generated by Django 5.2.1 on 2025-05-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_drinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
    ]
