# Generated by Django 5.2.1 on 2025-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='base_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PizzaType',
        ),
    ]
