# Generated by Django 5.2.1 on 2025-06-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_pizza_type_rename_base_price_pizza_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(blank=True, to='menu.drink'),
        ),
    ]
